import { v4 as uuid } from 'uuid';
export default [
  {
    id: uuid(),
    time: '8:30AM',
    tee: '|',
    player1: 'Nikhil Sharma (AM)',
    player2: 'Karan Mehto (Am)',
    player3: 'Umed (AM)',
    player4: 'Abhiraj Singh Benipal (A)',
  },
  {
    id: uuid(),
    time: '8:40AM',
    tee: '|',
    player1: 'Paramraj Sandhu (A)',
    player2: 'Abhyudaya Rawat (A)',
    player3: 'Ajaypal Bajwa (A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '8:50AM',
    tee: '|',
    player1: 'Pankaj Mishra (AM)',
    player2: 'Amanveer Singh (A)',
    player3: 'Shiv Kumar (AM)',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:00AM',
    tee: '|',
    player1: 'Hazel Chauhan (A)',
    player2: 'Mehar Nijjer (A)',
    player3: 'Aarushi Bhanot (A)',
    player4: '',
  },
  {
    id: uuid(),
    time: '9:10AM',
    tee: '|',
    player1: 'Manraj S Deol (B)',
    player2: 'Anupam Dahiya (B)',
    player3: 'Waris Kamboj (B)',
    player4: 'Ivan Jolly (B)',
  },
  {
    id: uuid(),
    time: '9:20AM',
    tee: '|',
    player1: 'Krish Chawla (B)',
    player2: 'Ajay Kumar (B)',
    player3: 'Iren Singh (B)',
    player4: 'Daksh Sihag (C)',
  },
  {
    id: uuid(),
    time: '9:30AM',
    tee: '|',
    player1: 'Pranav Khandelwal (B)',
    player2: 'Saurav Das (B)',
    player3: 'Rajyeveer Sultania (A)',
    player4: 'Karan Mahor (B)',
  },
  {
    id: uuid(),
    time: '9:40AM',
    tee: '|',
    player1: 'Henaaz (B)',
    player2: 'Mannat Brar (B)',
    player3: 'Ceerat Kang (B)',
    player4: ' ',
  },
  {
    id: uuid(),
    time: '9:50AM',
    tee: '|',
    player1: 'Rannvijay S Gill (C)',
    player2: 'Neil Jolly (C)',
    player3: 'Harjai Milkha Singh (C)',
    player4: 'Hriday Rialch (C)',
  },
  {
    id: uuid(),
    time: '10:00AM',
    tee: '|',
    player1: 'Aryaveer Singh Grewal (D)',
    player2: 'Vidit Aggarwal (D)',
    player3: 'Abhiraj (D)',
    player4: 'Ravikaran (D)',
  },
  {
    id: uuid(),
    time: '10:10AM',
    tee: '|',
    player1: 'Ayan Arora (D)',
    player2: 'Jubair Singh Dhaliwal (D)',
    player3: 'Pritheesh Inder Singh Kapoor (D)',
    player4: 'Arnav (D)',
  },
  {
    id: uuid(),
    time: '10:20AM',
    tee: '|',
    player1: 'Guneet Sekhon (C)',
    player2: 'Advika Datta (D)',
    player3: 'Tanvi Kaur (D)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:30AM',
    tee: '|',
    player1: 'Nihaal Cheema (E)',
    player2: 'Bhavea Sanjiv Rathee (E)',
    player3: 'Zorawer Sandhu (E)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:40AM',
    tee: '|',
    player1: 'Shiv Shankar Mandal (E)',
    player2: 'Zurawer Singh Chahal (E)',
    player3: 'Sahib Aujla (E)',
    player4: '',
  },
  {
    id: uuid(),
    time: '10:50AM',
    tee: '|',
    player1: 'Vishnu Mandal (E)',
    player2: 'Teghbir Singh Khattra (E)',
    player3: 'Jot Sarup (E)',
    player4: '',
  },
  {
    id: uuid(),
    time: '11:00AM',
    tee: '|',
    player1: 'Naina Kapoor (E)',
    player2: 'Divjot Gupta (E)',
    player3: 'Anay Aggarwal (E)',
    player4: '',
  }
];
